const demoGames = {
  "DEMO3208": {name: "5211", quantity: 1},
  "DEMO3053": {name: "100 things for little children to do on a trip", quantity: 1},
  "DEMO3223": {name: "100 Things For Little Children To Do On A Trip", quantity: 1},
  "DEMO1129": {name: "13 Days: Cuban Missile Crisis, 1962", quantity: 1},
  "DEMO1689": {name: "13 Dead End Drive", quantity: 1},
  "DEMO983": {name: "1775: American Revolution", quantity: 1},
  "DEMO1423": {name: "185 Graziella, Burano - William Carr 1000p", quantity: 1},
  "DEMO3111": {name: "3-in-1 Magnetic Chess, Checkers, Backgammon ", quantity: 1},
  "DEMO3112": {name: "3-in-1 Magnetic Chess, Checkers, Backgammon ", quantity: 1},
  "DEMO1197": {name: "4D Washington DC 1100p", quantity: 1},
  "DEMO3230": {name: "4x4 speed cube", quantity: 1},
  "DEMO1617": {name: "5 minute Marvel", quantity: 1},
  "DEMO5": {name: "7 Wonders", quantity: 1},
  "DEMO8": {name: "7 Wonders Duel", quantity: 1},
  "DEMO3043": {name: "A Fake Artist Goes to New York", quantity: 1},
  "DEMO1431": {name: "Acorn Soup", quantity: 1},
  "DEMO3014": {name: "Action Cats!", quantity: 1},
  "DEMO1363": {name: "Aggravation", quantity: 1},
  "DEMO16": {name: "Agricola", quantity: 1},
  "DEMO1751": {name: "Alala Love 500p", quantity: 1},
  "DEMO1217": {name: "Alfred Hitchcock 1000p", quantity: 1},
  "DEMO1524": {name: "Alphabet Go Fish", quantity: 1},
  "DEMO3136": {name: "Alphabet Go Fish", quantity: 1},
  "DEMO1424": {name: "Alphabet Train 28p", quantity: 1},
  "DEMO1173": {name: "Alphabet Train 28pc", quantity: 1},
  "DEMO3012": {name: "American flag Playing cards", quantity: 1},
  "DEMO1393": {name: "American State Birds 1000p", quantity: 1},
  "DEMO1112": {name: "Animal Rummy", quantity: 1},
  "DEMO34": {name: "Animal Upon Animal", quantity: 1},
  "DEMO1638": {name: "Animal upon Animal", quantity: 1},
  "DEMO1775": {name: "Animals of the World 25p", quantity: 1},
  "DEMO3008": {name: "Anomia", quantity: 1},
  "DEMO1184": {name: "Anomia Kids", quantity: 1},
  "DEMO37": {name: "Antidote", quantity: 1},
  "DEMO1685": {name: "Apocalyptic Picnic", quantity: 1},
  "DEMO38": {name: "Apples to Apples", quantity: 1},
  "DEMO1148": {name: "Apples to Apples", quantity: 1},
  "DEMO39": {name: "Apples to Apples Junior", quantity: 1},
  "DEMO1591": {name: "Arboretum", quantity: 1},
  "DEMO1609": {name: "Arboretum", quantity: 1},
  "DEMO1607": {name: "Architects of the West Kingdom", quantity: 1},
  "DEMO3007": {name: "Artsee", quantity: 1},
  "DEMO3045": {name: "Artsy Cats 500p", quantity: 1},
  "DEMO3009": {name: "Astrology Foil 1000p", quantity: 1},
  "DEMO3116": {name: "Atelier", quantity: 1},
  "DEMO1786": {name: "Atlantis Escape", quantity: 1},
  "DEMO3185": {name: "Atlantis Escape", quantity: 1},
  "DEMO795": {name: "Avalon", quantity: 1},
  "DEMO1270": {name: "Azul", quantity: 1},
  "DEMO1596": {name: "Azul", quantity: 1},
  "DEMO1623": {name: "Azul- Stained Glass of Sintra", quantity: 1},
  "DEMO3235": {name: "Back Spin", quantity: 1},
  "DEMO54": {name: "Backgammon", quantity: 1},
  "DEMO1314": {name: "Balance Beans", quantity: 1},
  "DEMO1532": {name: "Balance Beans", quantity: 1},
  "DEMO3195": {name: "Balance Beans", quantity: 1},
  "DEMO60": {name: "Bananagrams", quantity: 1},
  "DEMO3015": {name: "Bananagrams", quantity: 1},
  "DEMO3016": {name: "Bananagrams", quantity: 1},
  "DEMO62": {name: "Bang! -Bullet", quantity: 1},
  "DEMO1581": {name: "Bards Dispense Profanity", quantity: 1},
  "DEMO3062": {name: "Barenpark", quantity: 1},
  "DEMO3066": {name: "Bargain Quest", quantity: 1},
  "DEMO3061": {name: "Battle sheep", quantity: 1},
  "DEMO1588": {name: "Battlesheep", quantity: 1},
  "DEMO3145": {name: "Bears in Barrels", quantity: 1},
  "DEMO66": {name: "Betrayal at House on the Hill - Widow’s Walk Expansion included", quantity: 1},
  "DEMO68": {name: "Between two Cities with Capitals Expansion", quantity: 1},
  "DEMO70": {name: "Big Boggle", quantity: 1},
  "DEMO71": {name: "Big Boggle", quantity: 1},
  "DEMO1677": {name: "Blank & Blankdemic", quantity: 1},
  "DEMO3023": {name: "Blank & Blankdemic", quantity: 1},
  "DEMO1698": {name: "Bllox", quantity: 1},
  "DEMO72": {name: "Blokus", quantity: 1},
  "DEMO1083": {name: "Blokus", quantity: 1},
  "DEMO3207": {name: "Bloom", quantity: 1},
  "DEMO1450": {name: "Blue Lagoon", quantity: 1},
  "DEMO73": {name: "Blue Plate Scramble", quantity: 1},
  "DEMO74": {name: "Bohnanza", quantity: 1},
  "DEMO3044": {name: "Bon Voyage - Ireland 1000p", quantity: 1},
  "DEMO3078": {name: "Bosk", quantity: 1},
  "DEMO3010": {name: "Boss monster", quantity: 1},
  "DEMO3234": {name: "Brain Quest - grade 5", quantity: 1},
  "DEMO3233": {name: "Brain Quest Age 2-3", quantity: 1},
  "DEMO1784": {name: "Brain Train", quantity: 1},
  "DEMO79": {name: "Brandon the Brave", quantity: 1},
  "DEMO80": {name: "Brandon the Brave", quantity: 1},
  "DEMO3209": {name: "Bubble Tea", quantity: 1},
  "DEMO1526": {name: "Bugzzle", quantity: 1},
  "DEMO1310": {name: "Busy Airport 35p", quantity: 1},
  "DEMO3027": {name: "Cabo", quantity: 1},
  "DEMO1387": {name: "Cahoots", quantity: 1},
  "DEMO3135": {name: "Cahoots", quantity: 1},
  "DEMO1603": {name: "cake off!", quantity: 1},
  "DEMO1603": {name: "Cake Off!", quantity: 1},
  "DEMO3237": {name: "Calibron 12", quantity: 1},
  "DEMO1788": {name: "Calimala", quantity: 1},
  "DEMO1608": {name: "Camel Up", quantity: 1},
  "DEMO3083": {name: "Capital City", quantity: 1},
  "DEMO929": {name: "Captain Sonar", quantity: 1},
  "DEMO3085": {name: "Carcassonne", quantity: 1},
  "DEMO1147": {name: "Carcassonne with Princess and Dragon", quantity: 1},
  "DEMO3003": {name: "Cards Against Labyrinth", quantity: 1},
  "DEMO1755": {name: "Carpe Diem", quantity: 1},
  "DEMO102": {name: "Castle Logix", quantity: 1},
  "DEMO1127": {name: "Castle Logix", quantity: 1},
  "DEMO103": {name: "Castle Panic", quantity: 1},
  "DEMO104": {name: "Castles of Mad King Ludwig", quantity: 1},
  "DEMO1110": {name: "Cat Crimes", quantity: 1},
  "DEMO1258": {name: "Cat Crimes", quantity: 1},
  "DEMO3181": {name: "Cat Crimes", quantity: 1},
  "DEMO1435": {name: "Cat Lady", quantity: 1},
  "DEMO1385": {name: "Catan", quantity: 1},
  "DEMO640": {name: "Catan- Cities and Knights", quantity: 1},
  "DEMO1459": {name: "Catan Junior", quantity: 1},
  "DEMO591": {name: "Catan Rivals", quantity: 1},
  "DEMO3060": {name: "Catan Rivals", quantity: 1},
  "DEMO1737": {name: "Catch the moon", quantity: 1},
  "DEMO645": {name: "Catch!", quantity: 1},
  "DEMO112": {name: "Caverna", quantity: 1},
  "DEMO3142": {name: "Century A New World", quantity: 1},
  "DEMO3141": {name: "Century Eastern Wonders", quantity: 1},
  "DEMO991": {name: "Century Spice Road", quantity: 1},
  "DEMO3131": {name: "Cha-cha Chihuahua", quantity: 1},
  "DEMO3028": {name: "Channel A", quantity: 1},
  "DEMO3005": {name: "Checkers", quantity: 1},
  "DEMO3197": {name: "Cheeky Monkey", quantity: 1},
  "DEMO3004": {name: "Chess", quantity: 1},
  "DEMO1248": {name: "Chickyboom, Giant", quantity: 1},
  "DEMO1550": {name: "Chill Out!", quantity: 1},
  "DEMO1239": {name: "Chinese Chess", quantity: 1},
  "DEMO1312": {name: "Chocolate Fix", quantity: 1},
  "DEMO3177": {name: "Chocolate fix", quantity: 1},
  "DEMO3186": {name: "Chocolate Fix", quantity: 1},
  "DEMO127": {name: "Chrononauts", quantity: 1},
  "DEMO128": {name: "Chrononauts- Early American", quantity: 1},
  "DEMO129": {name: "Circuit Maze", quantity: 1},
  "DEMO1771": {name: "Circuit Maze", quantity: 1},
  "DEMO1308": {name: "Ciro Marchetti 750p", quantity: 1},
  "DEMO131": {name: "City Lights 750p", quantity: 1},
  "DEMO1288": {name: "Civilization- A New Dawn", quantity: 1},
  "DEMO1520": {name: "clack!", quantity: 1},
  "DEMO1520": {name: "Clack!", quantity: 1},
  "DEMO3206": {name: "Clack! Categories", quantity: 1},
  "DEMO1703": {name: "Clank!", quantity: 1},
  "DEMO3128": {name: "Clank! Expeditions: Temple of the Ape Lords", quantity: 1},
  "DEMO1134": {name: "Clank! In Space!", quantity: 1},
  "DEMO1396": {name: "Clans of Caledonia", quantity: 1},
  "DEMO133": {name: "Clear for Takeoff", quantity: 1},
  "DEMO1136": {name: "Clue (Classic)", quantity: 1},
  "DEMO1284": {name: "Clue Classic Edition", quantity: 1},
  "DEMO1278": {name: "Clue Suspect- Card Game", quantity: 1},
  "DEMO3218": {name: "Cluemaster", quantity: 1},
  "DEMO3219": {name: "Cluemaster", quantity: 1},
  "DEMO1718": {name: "CO2 Second Chance", quantity: 1},
  "DEMO3026": {name: "Cockroach Poker - Royal", quantity: 1},
  "DEMO140": {name: "Codenames", quantity: 1},
  "DEMO1133": {name: "Codenames", quantity: 1},
  "DEMO1086": {name: "Codenames- Duet", quantity: 1},
  "DEMO3035": {name: "Codenames- Duet", quantity: 1},
  "DEMO141": {name: "Codenames- Pictures", quantity: 1},
  "DEMO3037": {name: "Coggy", quantity: 1},
  "DEMO1536": {name: "Coimbra", quantity: 1},
  "DEMO3123": {name: "Colorama", quantity: 1},
  "DEMO1348": {name: "Colorful Bottles 1000p", quantity: 1},
  "DEMO1522": {name: "Colorful Marinara 500p", quantity: 1},
  "DEMO1300": {name: "Compose Yourself", quantity: 1},
  "DEMO148": {name: "Concept", quantity: 1},
  "DEMO1740": {name: "Concept", quantity: 1},
  "DEMO1668": {name: "Concept Kids", quantity: 1},
  "DEMO931": {name: "Concordia", quantity: 1},
  "DEMO149": {name: "Construction Jumbo 25p", quantity: 1},
  "DEMO1165": {name: "Construction Jumbo 25p", quantity: 1},
  "DEMO150": {name: "Continuo", quantity: 1},
  "DEMO3032": {name: "Corinth", quantity: 1},
  "DEMO153": {name: "Coup", quantity: 1},
  "DEMO154": {name: "Coup- Reformation", quantity: 1},
  "DEMO1750": {name: "Crankity", quantity: 1},
  "DEMO155": {name: "Crappy Birthday", quantity: 1},
  "DEMO3099": {name: "Crazy Cats", quantity: 1},
  "DEMO156": {name: "Creature Clash", quantity: 1},
  "DEMO3113": {name: "Cribbage four track", quantity: 1},
  "DEMO1337": {name: "Crows Overkill", quantity: 1},
  "DEMO3146": {name: "Cryptid", quantity: 1},
  "DEMO1515": {name: "Cuba 1000p", quantity: 1},
  "DEMO1708": {name: "Cube Puzzler Pro", quantity: 1},
  "DEMO1244": {name: "Cubeez", quantity: 1},
  "DEMO3031": {name: "Curios", quantity: 1},
  "DEMO3176": {name: "Cycles", quantity: 1},
  "DEMO170": {name: "Dead Last", quantity: 1},
  "DEMO1212": {name: "Decrypto", quantity: 1},
  "DEMO1117": {name: "Defeating the Basilisk 500p", quantity: 1},
  "DEMO1521": {name: "Deja vu", quantity: 1},
  "DEMO1204": {name: "Deluxe Pente", quantity: 1},
  "DEMO1205": {name: "Deluxe Pente", quantity: 1},
  "DEMO540": {name: "deluxe pit", quantity: 1},
  "DEMO3153": {name: "Detective Club", quantity: 1},
  "DEMO3248": {name: "Dice Stack", quantity: 1},
  "DEMO3174": {name: "Dimpl", quantity: 1},
  "DEMO1525": {name: "Dimpl duo", quantity: 1},
  "DEMO3052": {name: "Dinosaur 36p", quantity: 1},
  "DEMO1665": {name: "Dinosaur Book & Jigsaw 100p", quantity: 1},
  "DEMO1551": {name: "Dinosaur Escape", quantity: 1},
  "DEMO1643": {name: "Dinosaur Island", quantity: 1},
  "DEMO1782": {name: "Dinosaur Tea Party", quantity: 1},
  "DEMO1246": {name: "Distraction", quantity: 1},
  "DEMO1592": {name: "Dixit", quantity: 1},
  "DEMO1119": {name: "Dog Pile", quantity: 1},
  "DEMO3024": {name: "Doggy Disguise 100p", quantity: 1},
  "DEMO3160": {name: "Dominion", quantity: 1},
  "DEMO183": {name: "Dominion - Dark Ages", quantity: 1},
  "DEMO184": {name: "Dominion- Hinterlands", quantity: 1},
  "DEMO186": {name: "Dominion- Seaside", quantity: 1},
  "DEMO3006": {name: "Dominoes", quantity: 1},
  "DEMO1554": {name: "Dos", quantity: 1},
  "DEMO1558": {name: "Double Down", quantity: 1},
  "DEMO192": {name: "Double Shutter", quantity: 1},
  "DEMO896": {name: "Dr. Eureka", quantity: 1},
  "DEMO1087": {name: "Dr. Eureka", quantity: 1},
  "DEMO1451": {name: "Dr. Eureka", quantity: 1},
  "DEMO194": {name: "Dr. Eureka: Giant Demo", quantity: 1},
  "DEMO195": {name: "Dr. Eureka: Giant Demo", quantity: 1},
  "DEMO3084": {name: "Draftosaurus", quantity: 1},
  "DEMO198": {name: "Dragon Rapid Fire", quantity: 1},
  "DEMO3155": {name: "Dragon Realm", quantity: 1},
  "DEMO3228": {name: "Dragon wood", quantity: 1},
  "DEMO3159": {name: "Dragon's Breath", quantity: 1},
  "DEMO3151": {name: "Dragon's Cave", quantity: 1},
  "DEMO253": {name: "Drinking Fluxx", quantity: 1},
  "DEMO1343": {name: "Drop It", quantity: 1},
  "DEMO1731": {name: "Drop it", quantity: 1},
  "DEMO1539": {name: "Duck-A-Roo", quantity: 1},
  "DEMO3158": {name: "Dust in the Wings", quantity: 1},
  "DEMO995": {name: "Dutch Blitz", quantity: 1},
  "DEMO996": {name: "Dutch Blitz- Blue", quantity: 1},
  "DEMO1390": {name: "Edward Gorey 1000p", quantity: 1},
  "DEMO206": {name: "Eldritch Horror", quantity: 1},
  "DEMO3029": {name: "Elevenses", quantity: 1},
  "DEMO3221": {name: "Enchanted Forest", quantity: 1},
  "DEMO1568": {name: "Engine Engine No. 9", quantity: 1},
  "DEMO1601": {name: "Escape from the Hidden Castle", quantity: 1},
  "DEMO3069": {name: "Eternal - Chronicles is the Throne", quantity: 1},
  "DEMO215": {name: "Even Steven's Odd!", quantity: 1},
  "DEMO3036": {name: "Everyone Loves a Parade", quantity: 1},
  "DEMO216": {name: "Evolution", quantity: 1},
  "DEMO217": {name: "Evolution Climate", quantity: 1},
  "DEMO1634": {name: "Evolution- The Beginning", quantity: 1},
  "DEMO1661": {name: "Exploding Kittens", quantity: 1},
  "DEMO1162": {name: "Explorers of the North Sea", quantity: 1},
  "DEMO1399": {name: "Fallout", quantity: 1},
  "DEMO1285": {name: "Fastrack Mini", quantity: 1},
  "DEMO228": {name: "Feed the Woozle", quantity: 1},
  "DEMO229": {name: "Feed the Woozle", quantity: 1},
  "DEMO230": {name: "Feed the Woozle", quantity: 1},
  "DEMO232": {name: "Fiery Dragons", quantity: 1},
  "DEMO1626": {name: "Fireball Island", quantity: 1},
  "DEMO1713": {name: "Five Crowns", quantity: 1},
  "DEMO1183": {name: "Flags of the World 1000p", quantity: 1},
  "DEMO1048": {name: "Flamme Rouge", quantity: 1},
  "DEMO1143": {name: "Flower Fairy", quantity: 1},
  "DEMO3018": {name: "Flowers in Village - Kazuyuki Ohtsu 1000p", quantity: 1},
  "DEMO246": {name: "Fluxx", quantity: 1},
  "DEMO3021": {name: "Fluxx- Anatomy", quantity: 1},
  "DEMO250": {name: "Fluxx- Batman", quantity: 1},
  "DEMO251": {name: "Fluxx- Chemistry", quantity: 1},
  "DEMO252": {name: "Fluxx- Cthulhu", quantity: 1},
  "DEMO1138": {name: "Fluxx- Dr. Who", quantity: 1},
  "DEMO3019": {name: "Fluxx- Math", quantity: 1},
  "DEMO259": {name: "Fluxx- Pirate", quantity: 1},
  "DEMO261": {name: "Fluxx- Zombie", quantity: 1},
  "DEMO3022": {name: "Fluxx- Zombie", quantity: 1},
  "DEMO260": {name: "Fluxx-Star", quantity: 1},
  "DEMO1664": {name: "Foodie Fight", quantity: 1},
  "DEMO3025": {name: "For Sale", quantity: 1},
  "DEMO3030": {name: "For the Queen", quantity: 1},
  "DEMO265": {name: "Forbidden Desert", quantity: 1},
  "DEMO266": {name: "Forbidden Desert", quantity: 1},
  "DEMO267": {name: "Forbidden Desert", quantity: 1},
  "DEMO3104": {name: "Forbidden Desert", quantity: 1},
  "DEMO268": {name: "Forbidden Island", quantity: 1},
  "DEMO270": {name: "Forbidden Island", quantity: 1},
  "DEMO3216": {name: "Forbidden Island", quantity: 1},
  "DEMO1518": {name: "Forbidden Sky", quantity: 1},
  "DEMO1216": {name: "Foul Play & Cabernet 1000p", quantity: 1},
  "DEMO1577": {name: "Fox’s Party", quantity: 1},
  "DEMO1583": {name: "Frida's Fruit Fiesta", quantity: 1},
  "DEMO275": {name: "Friends and Neighbors", quantity: 1},
  "DEMO276": {name: "Friends and Neighbors", quantity: 1},
  "DEMO1548": {name: "Fruit Punch", quantity: 1},
  "DEMO1640": {name: "Fugitive", quantity: 1},
  "DEMO1719": {name: "Fugitive", quantity: 1},
  "DEMO3040": {name: "Game of Thrones- Hand of the King", quantity: 1},
  "DEMO1154": {name: "Game of Thrones: The Board Game", quantity: 1},
  "DEMO1690": {name: "Ganz Schön Celver (That’s pretty Clever)", quantity: 1},
  "DEMO1341": {name: "Geo Puzzle USA & Canada", quantity: 1},
  "DEMO547": {name: "Geography of the United States", quantity: 1},
  "DEMO285": {name: "Get Bit", quantity: 1},
  "DEMO286": {name: "Get Bit", quantity: 1},
  "DEMO287": {name: "Get Bit", quantity: 1},
  "DEMO288": {name: "Get Bit", quantity: 1},
  "DEMO1229": {name: "Get the MacGuffin", quantity: 1},
  "DEMO1230": {name: "Get the MacGuffin", quantity: 1},
  "DEMO1361": {name: "Ghost Fightin' Treasure Hunters", quantity: 1},
  "DEMO1199": {name: "Giant Fire Truck 24p", quantity: 1},
  "DEMO1425": {name: "Giant Fire Truck 24p", quantity: 1},
  "DEMO1426": {name: "Giant Firetruck 24p", quantity: 1},
  "DEMO3150": {name: "Giant Gobblet Gobblers", quantity: 1},
  "DEMO3147": {name: "Giant Pengoloo", quantity: 1},
  "DEMO1780": {name: "Gimme Gimme Guinea Pigs", quantity: 1},
  "DEMO1472": {name: "Gizmos", quantity: 1},
  "DEMO3047": {name: "Gloom", quantity: 1},
  "DEMO1461": {name: "Gnomes at Night", quantity: 1},
  "DEMO301": {name: "Go", quantity: 1},
  "DEMO1292": {name: "Go (Deluxe)", quantity: 1},
  "DEMO1523": {name: "Go away monster", quantity: 1},
  "DEMO1534": {name: "Go away monster", quantity: 1},
  "DEMO3168": {name: "Go Away Monster", quantity: 1},
  "DEMO1111": {name: "Go Fish", quantity: 1},
  "DEMO300": {name: "Go Go Gelato", quantity: 1},
  "DEMO1187": {name: "Go Nuts for Donuts", quantity: 1},
  "DEMO302": {name: "Gobblet Gobblers", quantity: 1},
  "DEMO303": {name: "Gobblet Gobblers", quantity: 1},
  "DEMO3201": {name: "Gobblet Gobblers: Giant Demo", quantity: 1},
  "DEMO304": {name: "Goblet gobblers", quantity: 1},
  "DEMO1769": {name: "Godsforge", quantity: 1},
  "DEMO919": {name: "Gonuts for Donuts", quantity: 1},
  "DEMO3192": {name: "Gonuts for Donuts", quantity: 1},
  "DEMO3130": {name: "GraviTrax", quantity: 1},
  "DEMO308": {name: "Gravity Maze", quantity: 1},
  "DEMO1299": {name: "Gravity Maze", quantity: 1},
  "DEMO3122": {name: "Gravity Maze", quantity: 1},
  "DEMO1358": {name: "Grimm Forest", quantity: 1},
  "DEMO1215": {name: "Grounds for Murder 1000p", quantity: 1},
  "DEMO316": {name: "Guillotine", quantity: 1},
  "DEMO1701": {name: "Gurms", quantity: 1},
  "DEMO1625": {name: "Hacker", quantity: 1},
  "DEMO3082": {name: "Hadara", quantity: 1},
  "DEMO3238": {name: "Hanoi tower", quantity: 1},
  "DEMO322": {name: "Happy Salmon", quantity: 1},
  "DEMO1351": {name: "Happy Salmon Blue", quantity: 1},
  "DEMO3187": {name: "Happy Salmon Green", quantity: 1},
  "DEMO1306": {name: "Harry Potter and the Half-Blood Prince 1000p", quantity: 1},
  "DEMO324": {name: "Harry Potter Hogwarts Battle", quantity: 1},
  "DEMO1394": {name: "Harry Potter Quidditch 1000p", quantity: 1},
  "DEMO3163": {name: "Haven", quantity: 1},
  "DEMO3120": {name: "Heads Talk Tails Walk", quantity: 1},
  "DEMO1220": {name: "Heaven & Ale", quantity: 1},
  "DEMO1602": {name: "Heimlich & Co.", quantity: 1},
  "DEMO909": {name: "Herbaceous", quantity: 1},
  "DEMO1107": {name: "Here, Fishy Fishy", quantity: 1},
  "DEMO3225": {name: "Here, Fishy Fishy!", quantity: 1},
  "DEMO988": {name: "Hero Realms", quantity: 1},
  "DEMO328": {name: "Hexago Continuo", quantity: 1},
  "DEMO3232": {name: "Hexagon 10", quantity: 1},
  "DEMO1504": {name: "High Society", quantity: 1},
  "DEMO1742": {name: "Hippogriff 200p", quantity: 1},
  "DEMO329": {name: "Hisss", quantity: 1},
  "DEMO1098": {name: "Hisss", quantity: 1},
  "DEMO1420": {name: "Historic Washington DC 1000p", quantity: 1},
  "DEMO548": {name: "History of the United States", quantity: 1},
  "DEMO1096": {name: "Hive", quantity: 1},
  "DEMO3164": {name: "Hive Mind", quantity: 1},
  "DEMO3042": {name: "Hokkaido", quantity: 1},
  "DEMO1720": {name: "Honga", quantity: 1},
  "DEMO333": {name: "Hoot Owl Hoot", quantity: 1},
  "DEMO334": {name: "Hoot Owl Hoot", quantity: 1},
  "DEMO1644": {name: "Hoot Owl Hoot", quantity: 1},
  "DEMO335": {name: "Hoot Owl Hoot!", quantity: 1},
  "DEMO1214": {name: "House of Boing", quantity: 1},
  "DEMO3051": {name: "Icarus", quantity: 1},
  "DEMO987": {name: "Ice Cool", quantity: 1},
  "DEMO1407": {name: "Ice Cool", quantity: 1},
  "DEMO3092": {name: "Ice Cool 2", quantity: 1},
  "DEMO341": {name: "Imagine", quantity: 1},
  "DEMO3067": {name: "Imhotep The Duel", quantity: 1},
  "DEMO1729": {name: "Imhotep with A New Dynasty Expansion included", quantity: 1},
  "DEMO974": {name: "Imploding Kittens", quantity: 1},
  "DEMO346": {name: "Incan Gold", quantity: 1},
  "DEMO1730": {name: "Ingenious", quantity: 1},
  "DEMO349": {name: "Innovation", quantity: 1},
  "DEMO3046": {name: "Insider", quantity: 1},
  "DEMO3129": {name: "Invasion of the Cow Snatchers", quantity: 1},
  "DEMO352": {name: "Iota", quantity: 1},
  "DEMO1188": {name: "Iota", quantity: 1},
  "DEMO356": {name: "Isle of Sky", quantity: 1},
  "DEMO358": {name: "Istanbul", quantity: 1},
  "DEMO3157": {name: "Istanbul: The Dice Game", quantity: 1},
  "DEMO1636": {name: "Jack & The Beanstalk", quantity: 1},
  "DEMO1388": {name: "Jane Wooster Scott - Celebration of America 1000p", quantity: 1},
  "DEMO1443": {name: "Jane Wooster Scott - Home Before Dark 1000p", quantity: 1},
  "DEMO3109": {name: "Jenga", quantity: 1},
  "DEMO3203": {name: "Jenga: Giant Version", quantity: 1},
  "DEMO1579": {name: "Just One", quantity: 1},
  "DEMO1674": {name: "K2", quantity: 1},
  "DEMO3161": {name: "Kaleidoscope Puzzle", quantity: 1},
  "DEMO1260": {name: "Kanagawa", quantity: 1},
  "DEMO3041": {name: "Kanoodle- Head to Head", quantity: 1},
  "DEMO1686": {name: "KeyForge Starter", quantity: 1},
  "DEMO1344": {name: "King of Technicolor", quantity: 1},
  "DEMO1210": {name: "King of Tokyo", quantity: 1},
  "DEMO379": {name: "Kingdomino", quantity: 1},
  "DEMO1365": {name: "Kingdomino", quantity: 1},
  "DEMO1454": {name: "Kingdomino: Age of Giants", quantity: 1},
  "DEMO957": {name: "Kingdomino: Giant Demo", quantity: 1},
  "DEMO1236": {name: "Kitty Bitty", quantity: 1},
  "DEMO1452": {name: "Kitty Bitty", quantity: 1},
  "DEMO1783": {name: "Kitty Paw", quantity: 1},
  "DEMO1345": {name: "Labyrinth", quantity: 1},
  "DEMO1656": {name: "Lanterns", quantity: 1},
  "DEMO390": {name: "Lanterns - The Harvest Festival", quantity: 1},
  "DEMO1151": {name: "Laser Chess", quantity: 1},
  "DEMO1641": {name: "Laser chess", quantity: 1},
  "DEMO392": {name: "Laser Maze", quantity: 1},
  "DEMO3124": {name: "Laser Maze", quantity: 1},
  "DEMO393": {name: "Last Letter", quantity: 1},
  "DEMO1437": {name: "Latches Board", quantity: 1},
  "DEMO3149": {name: "Legacy of Dragonholt", quantity: 1},
  "DEMO3143": {name: "Legend of the Five Rings LCG", quantity: 1},
  "DEMO437": {name: "Legendary", quantity: 1},
  "DEMO1433": {name: "Lemonade Shake Up", quantity: 1},
  "DEMO397": {name: "Leon the Dragon 58p", quantity: 1},
  "DEMO398": {name: "Leon the Dragon 58p", quantity: 1},
  "DEMO1309": {name: "Life Cycle of a Monarch Butterfly 48p", quantity: 1},
  "DEMO404": {name: "Life on Earth 20p", quantity: 1},
  "DEMO1778": {name: "Lion in my Way", quantity: 1},
  "DEMO3182": {name: "Lion in my Way", quantity: 1},
  "DEMO1777": {name: "Little Feminist Memory Match", quantity: 1},
  "DEMO410": {name: "Little Red Riding Hood", quantity: 1},
  "DEMO411": {name: "Little Red Riding Hood", quantity: 1},
  "DEMO3154": {name: "Little Red Riding Hood", quantity: 1},
  "DEMO1125": {name: "Little Red Riding Hood Deluxe", quantity: 1},
  "DEMO3188": {name: "Little Town", quantity: 1},
  "DEMO3039": {name: "Llama", quantity: 1},
  "DEMO1372": {name: "Long Cow", quantity: 1},
  "DEMO969": {name: "Lords of Waterdeep", quantity: 1},
  "DEMO417": {name: "Lords of Waterdeep: Scoundrels of Skullport Expansion", quantity: 1},
  "DEMO1753": {name: "Lost Cities", quantity: 1},
  "DEMO1637": {name: "Lost in the Woods", quantity: 1},
  "DEMO1759": {name: "Lots of Dogs 72p", quantity: 1},
  "DEMO422": {name: "Love Letter", quantity: 1},
  "DEMO3048": {name: "Love Letter- 2019 Edition", quantity: 1},
  "DEMO423": {name: "Love Letter- Premium Edition", quantity: 1},
  "DEMO1653": {name: "Machi Koro", quantity: 1},
  "DEMO3211": {name: "Mad Libs The Game", quantity: 1},
  "DEMO1209": {name: "Magic Maze", quantity: 1},
  "DEMO3236": {name: "Magna tiles", quantity: 1},
  "DEMO3222": {name: "Maki Stack", quantity: 1},
  "DEMO433": {name: "Mancala", quantity: 1},
  "DEMO1527": {name: "Map of the U.S.A.", quantity: 1},
  "DEMO1652": {name: "Marble Circuit", quantity: 1},
  "DEMO1118": {name: "Mars Explorers Wanted 500p", quantity: 1},
  "DEMO436": {name: "Mars Visions of the Future 1000p", quantity: 1},
  "DEMO438": {name: "Mascarade", quantity: 1},
  "DEMO3172": {name: "Math Dice", quantity: 1},
  "DEMO442": {name: "Math Dice Jr.", quantity: 1},
  "DEMO3193": {name: "Math Dice Jr.", quantity: 1},
  "DEMO3050": {name: "Medium", quantity: 1},
  "DEMO786": {name: "Memory Palace", quantity: 1},
  "DEMO1645": {name: "Memory Palace", quantity: 1},
  "DEMO3079": {name: "Mental Blocks", quantity: 1},
  "DEMO3139": {name: "Menu Masters", quantity: 1},
  "DEMO1475": {name: "Mercado", quantity: 1},
  "DEMO1635": {name: "Merlin", quantity: 1},
  "DEMO148": {name: "Mermaid Island", quantity: 1},
  "DEMO449": {name: "Mermaid Island", quantity: 1},
  "DEMO450": {name: "Mermaid Island", quantity: 1},
  "DEMO451": {name: "Mexican Train Dominoes", quantity: 1},
  "DEMO453": {name: "Mille Bornes", quantity: 1},
  "DEMO3126": {name: "Mind Block", quantity: 1},
  "DEMO1241": {name: "Mindo", quantity: 1},
  "DEMO1242": {name: "Mindo My First Logic Game", quantity: 1},
  "DEMO1370": {name: "Minecraft Card Game", quantity: 1},
  "DEMO1149": {name: "Mini Squigz", quantity: 1},
  "DEMO1168": {name: "Mini Squigz", quantity: 1},
  "DEMO3074": {name: "Mission X-Code", quantity: 1},
  "DEMO3169": {name: "Mobi", quantity: 1},
  "DEMO3165": {name: "Mobi Kids", quantity: 1},
  "DEMO1434": {name: "Monkey Around", quantity: 1},
  "DEMO463": {name: "Monopoly (Classic)", quantity: 1},
  "DEMO3132": {name: "Monopoly (Classic)", quantity: 1},
  "DEMO1203": {name: "Monopoly Deal", quantity: 1},
  "DEMO3179": {name: "Monster Match", quantity: 1},
  "DEMO3167": {name: "monster match game", quantity: 1},
  "DEMO3156": {name: "Monza", quantity: 1},
  "DEMO1781": {name: "Morphy", quantity: 1},
  "DEMO3105": {name: "Most Wanted", quantity: 1},
  "DEMO3081": {name: "Mountains", quantity: 1},
  "DEMO1666": {name: "Move & Groove", quantity: 1},
  "DEMO473": {name: "Munchkin", quantity: 1},
  "DEMO1259": {name: "Munchkin", quantity: 1},
  "DEMO1382": {name: "Muse", quantity: 1},
  "DEMO3148": {name: "My First Bananagrams", quantity: 1},
  "DEMO1339": {name: "My First Carcass", quantity: 1},
  "DEMO1711": {name: "My First Castle Panic", quantity: 1},
  "DEMO1739": {name: "My First Castle Panic", quantity: 1},
  "DEMO1739": {name: "My First Castle Panic", quantity: 1},
  "DEMO1378": {name: "My First Orchard", quantity: 1},
  "DEMO477": {name: "My First Stone Age", quantity: 1},
  "DEMO478": {name: "Mysterium", quantity: 1},
  "DEMO482": {name: "Mystic Vale: includes Vale of Magic expansion", quantity: 1},
  "DEMO1137": {name: "Nanofictionary", quantity: 1},
  "DEMO485": {name: "Natural Science 100p", quantity: 1},
  "DEMO1710": {name: "Nevertheless, She Persisted 1000pc", quantity: 1},
  "DEMO1621": {name: "Newton", quantity: 1},
  "DEMO492": {name: "No Stress Chess", quantity: 1},
  "DEMO493": {name: "No Stress Chess", quantity: 1},
  "DEMO1613": {name: "No Thanks!", quantity: 1},
  "DEMO1760": {name: "Noctiluca", quantity: 1},
  "DEMO548": {name: "noggins: history of the united states", quantity: 1},
  "DEMO497": {name: "Numbers League", quantity: 1},
  "DEMO1649": {name: "Nyctophobia", quantity: 1},
  "DEMO502": {name: "Odin’s Ravens", quantity: 1},
  "DEMO1113": {name: "Old Maid", quantity: 1},
  "DEMO3138": {name: "Once Upon a Castle", quantity: 1},
  "DEMO505": {name: "Once upon a Time", quantity: 1},
  "DEMO507": {name: "One Night Ultimate Werewolf", quantity: 1},
  "DEMO3056": {name: "Onitama", quantity: 1},
  "DEMO3191": {name: "Oombee Ball", quantity: 1},
  "DEMO3199": {name: "Oombee Cube", quantity: 1},
  "DEMO1544": {name: "Orbis", quantity: 1},
  "DEMO1545": {name: "Orbis Playmat", quantity: 1},
  "DEMO1538": {name: "Our World Jumbo 25p", quantity: 1},
  "DEMO550": {name: "Outer Space", quantity: 1},
  "DEMO512": {name: "Outfoxed", quantity: 1},
  "DEMO1561": {name: "Outfoxed", quantity: 1},
  "DEMO1779": {name: "Outfoxed", quantity: 1},
  "DEMO1681": {name: "Paku Paku", quantity: 1},
  "DEMO1704": {name: "Panda Rollers", quantity: 1},
  "DEMO516": {name: "Pandemic", quantity: 1},
  "DEMO1630": {name: "Pandemic Fall of Rome", quantity: 1},
  "DEMO1470": {name: "Pantone", quantity: 1},
  "DEMO1501": {name: "Paper Tales", quantity: 1},
  "DEMO1448": {name: "Paperback- Unabridged", quantity: 1},
  "DEMO1692": {name: "Patchwork", quantity: 1},
  "DEMO3058": {name: "Patchwork", quantity: 1},
  "DEMO3134": {name: "Pathfinder Adventure Card Game - Core Set", quantity: 1},
  "DEMO3241": {name: "Peg Jump 6", quantity: 1},
  "DEMO3202": {name: "Pengaloo: Giant Demo", quantity: 1},
  "DEMO526": {name: "Pengoloo", quantity: 1},
  "DEMO1088": {name: "Pengoloo", quantity: 1},
  "DEMO3217": {name: "Perfection", quantity: 1},
  "DEMO3133": {name: "Photosynthesis", quantity: 1},
  "DEMO1709": {name: "Pickles to Penguins", quantity: 1},
  "DEMO3144": {name: "Pictionary", quantity: 1},
  "DEMO1279": {name: "Pig 10", quantity: 1},
  "DEMO535": {name: "Pina Pirata", quantity: 1},
  "DEMO3086": {name: "Pipeline", quantity: 1},
  "DEMO539": {name: "Pit", quantity: 1},
  "DEMO540": {name: "Pit Deluxe", quantity: 1},
  "DEMO1756": {name: "Planet", quantity: 1},
  "DEMO1757": {name: "Planet", quantity: 1},
  "DEMO1340": {name: "Play Smart Dice", quantity: 1},
  "DEMO1234": {name: "Playing Cards Aviator", quantity: 1},
  "DEMO1746": {name: "Playing cards- Springbok", quantity: 1},
  "DEMO3057": {name: "Point Salad", quantity: 1},
  "DEMO541": {name: "Political World Map 1000p", quantity: 1},
  "DEMO1421": {name: "Politics 1000p", quantity: 1},
  "DEMO1213": {name: "Pool Party", quantity: 1},
  "DEMO542": {name: "Positano 500p", quantity: 1},
  "DEMO3212": {name: "Potato Pirate", quantity: 1},
  "DEMO1582": {name: "Potato Pirates", quantity: 1},
  "DEMO544": {name: "Power Grid", quantity: 1},
  "DEMO551": {name: "Presidents of the United States", quantity: 1},
  "DEMO1687": {name: "Pretty pretty princess", quantity: 1},
  "DEMO3049": {name: "Princess Party 100p", quantity: 1},
  "DEMO554": {name: "Puerto Rico", quantity: 1},
  "DEMO1767": {name: "Punto", quantity: 1},
  "DEMO1682": {name: "Push", quantity: 1},
  "DEMO1564": {name: "Puzz'Art Octopus 350p", quantity: 1},
  "DEMO1565": {name: "Puzz'Art Seahorse 350p", quantity: 1},
  "DEMO1251": {name: "Pylos", quantity: 1},
  "DEMO3239": {name: "Q’ba Maze", quantity: 1},
  "DEMO1254": {name: "Quarto", quantity: 1},
  "DEMO1255": {name: "Quarto", quantity: 1},
  "DEMO3054": {name: "Quiddler", quantity: 1},
  "DEMO3215": {name: "Quiddler Junior", quantity: 1},
  "DEMO1257": {name: "Quixo", quantity: 1},
  "DEMO1252": {name: "Quoridor", quantity: 1},
  "DEMO1253": {name: "Quoridor", quantity: 1},
  "DEMO1056": {name: "Qwirkle", quantity: 1},
  "DEMO1732": {name: "Qwirkle Rummy", quantity: 1},
  "DEMO1672": {name: "Qwixx Deluxe", quantity: 1},
  "DEMO1552": {name: "Race to the Treasure", quantity: 1},
  "DEMO573": {name: "Race to the Treasure!", quantity: 1},
  "DEMO575": {name: "Race to the treasure!", quantity: 1},
  "DEMO1765": {name: "Race to the Treasure!", quantity: 1},
  "DEMO2878": {name: "Race to the treasure!", quantity: 1},
  "DEMO3064": {name: "Ragusa", quantity: 1},
  "DEMO1120": {name: "Raiders of the North Sea", quantity: 1},
  "DEMO1610": {name: "Railroad ink", quantity: 1},
  "DEMO1200": {name: "Rainbow Caterpillar", quantity: 1},
  "DEMO3033": {name: "Rainbow Stacker", quantity: 1},
  "DEMO3055": {name: "Ramen Fury", quantity: 1},
  "DEMO577": {name: "Rat a tat Cat", quantity: 1},
  "DEMO578": {name: "Rat a tat Cat", quantity: 1},
  "DEMO579": {name: "Rat a tat Cat", quantity: 1},
  "DEMO1533": {name: "Rat-a-Tat Cat", quantity: 1},
  "DEMO3059": {name: "Ravine", quantity: 1},
  "DEMO3204": {name: "Ravnica Inquisition", quantity: 1},
  "DEMO1419": {name: "Readers' Paradise 1000p", quantity: 1},
  "DEMO1680": {name: "Reykholt", quantity: 1},
  "DEMO587": {name: "Rhino Hero", quantity: 1},
  "DEMO1574": {name: "Rhino Hero", quantity: 1},
  "DEMO1462": {name: "Ribbon Ninja", quantity: 1},
  "DEMO1482": {name: "Ribbon Ninja", quantity: 1},
  "DEMO938": {name: "Richard Scarry's Busytown Eye Found It!", quantity: 1},
  "DEMO1347": {name: "Richard Scarry's Busytown Eye Found It!", quantity: 1},
  "DEMO3220": {name: "Rivers, Roads & Rails", quantity: 1},
  "DEMO595": {name: "Robot Turtles", quantity: 1},
  "DEMO3152": {name: "Roll & Play", quantity: 1},
  "DEMO1792": {name: "Roll Again Maze", quantity: 1},
  "DEMO3190": {name: "Roll Again Sorter", quantity: 1},
  "DEMO3189": {name: "Roll Again Spinner", quantity: 1},
  "DEMO1748": {name: "Roll Again Tower", quantity: 1},
  "DEMO1301": {name: "Roller Coaster Challenge", quantity: 1},
  "DEMO3119": {name: "Roller Coaster Challenge", quantity: 1},
  "DEMO3020": {name: "Rooftop Garden 500p", quantity: 1},
  "DEMO3125": {name: "Root", quantity: 1},
  "DEMO605": {name: "Rory's Story Cubes", quantity: 1},
  "DEMO606": {name: "Rory's Story Cubes Actions", quantity: 1},
  "DEMO607": {name: "Royal Roundup", quantity: 1},
  "DEMO3229": {name: "Rubik's Star", quantity: 1},
  "DEMO3076": {name: "Running With The Bulls", quantity: 1},
  "DEMO1324": {name: "Rush Hour", quantity: 1},
  "DEMO3183": {name: "Rush Hour", quantity: 1},
  "DEMO614": {name: "Saboteur", quantity: 1},
  "DEMO1557": {name: "Saboteur", quantity: 1},
  "DEMO1735": {name: "Saboteur: The Lost Mines", quantity: 1},
  "DEMO3114": {name: "Sagrada", quantity: 1},
  "DEMO1401": {name: "Sailing Toward Osiris", quantity: 1},
  "DEMO1069": {name: "Santorini", quantity: 1},
  "DEMO1736": {name: "Santorini", quantity: 1},
  "DEMO3117": {name: "Santorini", quantity: 1},
  "DEMO621": {name: "Say Anything", quantity: 1},
  "DEMO1360": {name: "Say Anything", quantity: 1},
  "DEMO623": {name: "Say Anything Family Edition", quantity: 1},
  "DEMO1471": {name: "Scarabya", quantity: 1},
  "DEMO627": {name: "Scrabble", quantity: 1},
  "DEMO1281": {name: "Scrabble Slam!", quantity: 1},
  "DEMO631": {name: "Scythe", quantity: 1},
  "DEMO1563": {name: "Secret Code 13+4", quantity: 1},
  "DEMO1468": {name: "Seek-a-Boo!", quantity: 1},
  "DEMO635": {name: "Senet", quantity: 1},
  "DEMO946": {name: "Sequence", quantity: 1},
  "DEMO1170": {name: "Sequence Letters", quantity: 1},
  "DEMO1611": {name: "Set", quantity: 1},
  "DEMO3073": {name: "Set", quantity: 1},
  "DEMO3075": {name: "Set", quantity: 1},
  "DEMO637": {name: "Set Junior", quantity: 1},
  "DEMO927": {name: "Settlers of Catan", quantity: 1},
  "DEMO639": {name: "Settlers of Catan 5-6 Player", quantity: 1},
  "DEMO1633": {name: "Shadows - Amsterdam", quantity: 1},
  "DEMO645": {name: "Sheriff of Nottingham", quantity: 1},
  "DEMO3162": {name: "Sherlock Express", quantity: 1},
  "DEMO1218": {name: "Sherlock Holmes 1000p", quantity: 1},
  "DEMO3071": {name: "Ship Shape", quantity: 1},
  "DEMO3106": {name: "Shutter Bug", quantity: 1},
  "DEMO1758": {name: "Silicon Valley Start Ups", quantity: 1},
  "DEMO3140": {name: "Skip-Bo", quantity: 1},
  "DEMO3068": {name: "Skull", quantity: 1},
  "DEMO3070": {name: "Skull", quantity: 1},
  "DEMO652": {name: "Slamwich", quantity: 1},
  "DEMO3178": {name: "Sleeping Beauty", quantity: 1},
  "DEMO653": {name: "Sleeping Queens", quantity: 1},
  "DEMO655": {name: "Sleeping Queens", quantity: 1},
  "DEMO656": {name: "Sleeping Queens", quantity: 1},
  "DEMO657": {name: "Sleeping Queens", quantity: 1},
  "DEMO1590": {name: "Sleeping Queens", quantity: 1},
  "DEMO3226": {name: "Sleeping Queens", quantity: 1},
  "DEMO3077": {name: "Slide Quest", quantity: 1},
  "DEMO658": {name: "Small World", quantity: 1},
  "DEMO1126": {name: "Smart car 5x5", quantity: 1},
  "DEMO1411": {name: "Smart car 5x5", quantity: 1},
  "DEMO1785": {name: "Smart Farmer", quantity: 1},
  "DEMO1766": {name: "Smartmax", quantity: 1},
  "DEMO3198": {name: "Smarty cube", quantity: 1},
  "DEMO3121": {name: "Smash Up - The Big Geeky Box with Expansions", quantity: 1},
  "DEMO3089": {name: "Smash Up- World Tour: Culture Shock", quantity: 1},
  "DEMO1741": {name: "Snail Sprint!", quantity: 1},
  "DEMO1683": {name: "Snail’s Pace Race", quantity: 1},
  "DEMO3245": {name: "Snake", quantity: 1},
  "DEMO673": {name: "Snug as a Bug in a Rug", quantity: 1},
  "DEMO2875": {name: "Snug as a bug in a rug!", quantity: 1},
  "DEMO1293": {name: "Solar System Floor Puzzle 48p", quantity: 1},
  "DEMO1725": {name: "Solenia", quantity: 1},
  "DEMO677": {name: "Solitaire Chess", quantity: 1},
  "DEMO679": {name: "Solitaire Chess", quantity: 1},
  "DEMO680": {name: "Solitaire Chess", quantity: 1},
  "DEMO3110": {name: "Solitaire Chess", quantity: 1},
  "DEMO3242": {name: "Soma cube", quantity: 1},
  "DEMO3247": {name: "Soma cube", quantity: 1},
  "DEMO1439": {name: "Space Base", quantity: 1},
  "DEMO1647": {name: "Space Escape", quantity: 1},
  "DEMO1648": {name: "Space Escape", quantity: 1},
  "DEMO1762": {name: "Space Escape", quantity: 1},
  "DEMO1764": {name: "Space Escape", quantity: 1},
  "DEMO1303": {name: "Space Explorers 1000p", quantity: 1},
  "DEMO1176": {name: "Space Matching Game", quantity: 1},
  "DEMO1403": {name: "Spaceteam", quantity: 1},
  "DEMO3213": {name: "Spanish Bingo", quantity: 1},
  "DEMO3214": {name: "Spanish Vocabulary Bingo", quantity: 1},
  "DEMO1723": {name: "Spirit Island", quantity: 1},
  "DEMO3115": {name: "Splendor", quantity: 1},
  "DEMO690": {name: "Spot It", quantity: 1},
  "DEMO691": {name: "Spot It", quantity: 1},
  "DEMO1196": {name: "Spot It", quantity: 1},
  "DEMO1414": {name: "Spot It", quantity: 1},
  "DEMO692": {name: "Spot It Alphabet", quantity: 1},
  "DEMO1415": {name: "Spot it jr! animals", quantity: 1},
  "DEMO689": {name: "Spot It!", quantity: 1},
  "DEMO698": {name: "spot it! numbers and shapes", quantity: 1},
  "DEMO700": {name: "Spot-It", quantity: 1},
  "DEMO1598": {name: "Spring on Park 1000p", quantity: 1},
  "DEMO3107": {name: "Spy Master", quantity: 1},
  "DEMO701": {name: "Spyfall", quantity: 1},
  "DEMO1166": {name: "Spyfall 2", quantity: 1},
  "DEMO3173": {name: "Squigz", quantity: 1},
  "DEMO3194": {name: "Squigz 2.0", quantity: 1},
  "DEMO704": {name: "Stack up!", quantity: 1},
  "DEMO705": {name: "Stack Up!", quantity: 1},
  "DEMO3087": {name: "Star Trek Chrono-Trek", quantity: 1},
  "DEMO1231": {name: "Star Wars Legion", quantity: 1},
  "DEMO1469": {name: "Star Wars X-Wing", quantity: 1},
  "DEMO1537": {name: "Start-ups", quantity: 1},
  "DEMO1571": {name: "Stone Age", quantity: 1},
  "DEMO714": {name: "Story Line: Fairy Tales", quantity: 1},
  "DEMO715": {name: "Story Line: Scary Tales", quantity: 1},
  "DEMO718": {name: "Stratego", quantity: 1},
  "DEMO1181": {name: "Stuffed Fables", quantity: 1},
  "DEMO723": {name: "Suburbia", quantity: 1},
  "DEMO1776": {name: "Summer at the Amusement Park 500p", quantity: 1},
  "DEMO3166": {name: "Sumoku", quantity: 1},
  "DEMO1392": {name: "Sunset at Baker Beach 1000p", quantity: 1},
  "DEMO1696": {name: "Sunset Over Water", quantity: 1},
  "DEMO3090": {name: "Superfight", quantity: 1},
  "DEMO736": {name: "Sushi Go Party", quantity: 1},
  "DEMO954": {name: "Sushi Go Party!", quantity: 1},
  "DEMO737": {name: "Sushi Go!", quantity: 1},
  "DEMO1754": {name: "Sushi Roll", quantity: 1},
  "DEMO739": {name: "Suspend", quantity: 1},
  "DEMO740": {name: "Suspend", quantity: 1},
  "DEMO1511": {name: "Suspicion", quantity: 1},
  "DEMO1463": {name: "Swipe Shot", quantity: 1},
  "DEMO1464": {name: "Swipe Shot", quantity: 1},
  "DEMO3180": {name: "Swipe Shot", quantity: 1},
  "DEMO3184": {name: "Swish", quantity: 1},
  "DEMO1157": {name: "T.I.M.E Stories", quantity: 1},
  "DEMO3170": {name: "Tacto", quantity: 1},
  "DEMO1559": {name: "Take 5, Take a Number", quantity: 1},
  "DEMO743": {name: "Takenoko", quantity: 1},
  "DEMO748": {name: "Tangoes Jr.", quantity: 1},
  "DEMO749": {name: "Tangoes Jr.", quantity: 1},
  "DEMO3246": {name: "Tangram", quantity: 1},
  "DEMO3196": {name: "Tegu tower", quantity: 1},
  "DEMO755": {name: "Telestrations 12 player Party Pack", quantity: 1},
  "DEMO756": {name: "Tell Tale", quantity: 1},
  "DEMO757": {name: "Tell Tale", quantity: 1},
  "DEMO950": {name: "Terraforming Mars", quantity: 1},
  "DEMO3108": {name: "Terror Below", quantity: 1},
  "DEMO3065": {name: "Tesla vs. Edison", quantity: 1},
  "DEMO764": {name: "The Bloody Inn", quantity: 1},
  "DEMO767": {name: "The Castles of Burgundy - Card Game", quantity: 1},
  "DEMO1368": {name: "The Castles of Burgundy -Dice Game", quantity: 1},
  "DEMO3243": {name: "The Cruiser", quantity: 1},
  "DEMO773": {name: "The Fairy Game", quantity: 1},
  "DEMO1449": {name: "The Fairy Game", quantity: 1},
  "DEMO906": {name: "The Fox in the Forest", quantity: 1},
  "DEMO1693": {name: "The Game", quantity: 1},
  "DEMO3038": {name: "The Game", quantity: 1},
  "DEMO402": {name: "The Game of Life", quantity: 1},
  "DEMO1412": {name: "The Game of Life", quantity: 1},
  "DEMO1422": {name: "The Gardener's Palette 1000p", quantity: 1},
  "DEMO3100": {name: "The Great Dragon Race", quantity: 1},
  "DEMO780": {name: "The Grizzled", quantity: 1},
  "DEMO1374": {name: "The Hearmees", quantity: 1},
  "DEMO784": {name: "The Magic Labyrinth", quantity: 1},
  "DEMO787": {name: "The memory palace", quantity: 1},
  "DEMO1507": {name: "The Mind", quantity: 1},
  "DEMO1631": {name: "The Mind", quantity: 1},
  "DEMO794": {name: "The Resistance", quantity: 1},
  "DEMO1600": {name: "The River", quantity: 1},
  "DEMO630": {name: "The Scrambled States of America", quantity: 1},
  "DEMO1307": {name: "The Sistine Chapel 1000p", quantity: 1},
  "DEMO3001": {name: "The Sixties", quantity: 1},
  "DEMO3017": {name: "The Sixties 1000p", quantity: 1},
  "DEMO799": {name: "Think ‘N Sync", quantity: 1},
  "DEMO3013": {name: "Thinking Putty Puzzle", quantity: 1},
  "DEMO3200": {name: "Thirty Six Ocean Animals", quantity: 1},
  "DEMO1567": {name: "Thirty Six Ocean Animals 300p", quantity: 1},
  "DEMO1789": {name: "Thirty Six Wild Animals 100p", quantity: 1},
  "DEMO3227": {name: "Thirty Six Wild Animals 100p", quantity: 1},
  "DEMO1408": {name: "Three Little Piggies", quantity: 1},
  "DEMO1409": {name: "Three Little Piggies Deluxe", quantity: 1},
  "DEMO1094": {name: "Three Little Piggies: Deluxe", quantity: 1},
  "DEMO1605": {name: "Thumbs Up!", quantity: 1},
  "DEMO1275": {name: "Ticket to Ride", quantity: 1},
  "DEMO807": {name: "Ticket to Ride Asia", quantity: 1},
  "DEMO808": {name: "Ticket to Ride Europe", quantity: 1},
  "DEMO809": {name: "Ticket to Ride Rails and Sails", quantity: 1},
  "DEMO1676": {name: "Time Breaker", quantity: 1},
  "DEMO3063": {name: "Time Chase", quantity: 1},
  "DEMO816": {name: "Timeline", quantity: 1},
  "DEMO814": {name: "Timeline: American History", quantity: 1},
  "DEMO815": {name: "Timeline: Diversity", quantity: 1},
  "DEMO813": {name: "Timeline: Historical Events", quantity: 1},
  "DEMO817": {name: "Timeline: Music and Cinema", quantity: 1},
  "DEMO1174": {name: "Times Square, NYC 1000p", quantity: 1},
  "DEMO1743": {name: "Tiny Towns", quantity: 1},
  "DEMO1243": {name: "Tofu Kingdom", quantity: 1},
  "DEMO1629": {name: "Tofu Kingdom", quantity: 1},
  "DEMO819": {name: "Tokaido", quantity: 1},
  "DEMO1651": {name: "Tokyo Highway", quantity: 1},
  "DEMO820": {name: "Too Many Monkeys", quantity: 1},
  "DEMO821": {name: "Too Many Monkeys", quantity: 1},
  "DEMO1529": {name: "Touch and Feel Eric Carle 4x3p", quantity: 1},
  "DEMO3244": {name: "T-puzzle", quantity: 1},
  "DEMO3072": {name: "Trapwords", quantity: 1},
  "DEMO1442": {name: "Trash Pandas", quantity: 1},
  "DEMO1650": {name: "Trash Pandas", quantity: 1},
  "DEMO1673": {name: "Trash Pandas", quantity: 1},
  "DEMO3097": {name: "Treasure Island", quantity: 1},
  "DEMO1510": {name: "Trekking The National Parks", quantity: 1},
  "DEMO1733": {name: "Trekking The National Parks", quantity: 1},
  "DEMO1691": {name: "Troika", quantity: 1},
  "DEMO826": {name: "Trouble", quantity: 1},
  "DEMO826": {name: "Trouble", quantity: 1},
  "DEMO3171": {name: "Trucky 3", quantity: 1},
  "DEMO3224": {name: "Trucky 3", quantity: 1},
  "DEMO829": {name: "Tsuro", quantity: 1},
  "DEMO1492": {name: "Tumball", quantity: 1},
  "DEMO3127": {name: "Tumble Maze", quantity: 1},
  "DEMO1570": {name: "Twin It", quantity: 1},
  "DEMO1724": {name: "Two Rooms and a Boom with Necroboomicon Expansion", quantity: 1},
  "DEMO1717": {name: "Two Sided Tiger 24p", quantity: 1},
  "DEMO1727": {name: "Ubongo!", quantity: 1},
  "DEMO1697": {name: "Ultimo", quantity: 1},
  "DEMO3002": {name: "Underwater Cities", quantity: 1},
  "DEMO3093": {name: "Underwater Cities", quantity: 1},
  "DEMO838": {name: "Unicorn Glitterluck", quantity: 1},
  "DEMO1639": {name: "Unicorn Glitterluck", quantity: 1},
  "DEMO840": {name: "Uno", quantity: 1},
  "DEMO841": {name: "Uno", quantity: 1},
  "DEMO842": {name: "Uno", quantity: 1},
  "DEMO3088": {name: "Uno", quantity: 1},
  "DEMO1675": {name: "Uno Moo", quantity: 1},
  "DEMO1642": {name: "Uno Moo!", quantity: 1},
  "DEMO1747": {name: "Unocorns", quantity: 1},
  "DEMO3034": {name: "USA Lighthouse 550p", quantity: 1},
  "DEMO1566": {name: "USA Map 200p", quantity: 1},
  "DEMO846": {name: "Vast - The Crystal Caverns", quantity: 1},
  "DEMO3094": {name: "Victorian Masterminds", quantity: 1},
  "DEMO1620": {name: "Villainous", quantity: 1},
  "DEMO1395": {name: "Visit Mars 1000p", quantity: 1},
  "DEMO3210": {name: "Visitor in Blackwood Grove", quantity: 1},
  "DEMO1043": {name: "Viticulture - Essential Edition", quantity: 1},
  "DEMO1787": {name: "Votes for Women 500p", quantity: 1},
  "DEMO3098": {name: "Walking in Burano", quantity: 1},
  "DEMO3091": {name: "War Chest", quantity: 1},
  "DEMO3095": {name: "Warsaw: City of Ruins", quantity: 1},
  "DEMO3240": {name: "Washington 555 tower", quantity: 1},
  "DEMO1546": {name: "Washington DC Mall 500p", quantity: 1},
  "DEMO854": {name: "Washington DC Metro Puzzle 1000p", quantity: 1},
  "DEMO3205": {name: "Watergate", quantity: 1},
  "DEMO858": {name: "We Didn’t Playtest This at All", quantity: 1},
  "DEMO860": {name: "We Didn’t Playtest This:Legacies", quantity: 1},
  "DEMO3080": {name: "We’re Doomed!", quantity: 1},
  "DEMO861": {name: "Welcome to the Dungeon", quantity: 1},
  "DEMO992": {name: "Welcome to the Dungeon", quantity: 1},
  "DEMO1575": {name: "Welcome to Your Perfect Home", quantity: 1},
  "DEMO3101": {name: "Werewords", quantity: 1},
  "DEMO3096": {name: "What the Heck", quantity: 1},
  "DEMO1658": {name: "Who Did It", quantity: 1},
  "DEMO863": {name: "Wig Out!", quantity: 1},
  "DEMO864": {name: "Wig Out!", quantity: 1},
  "DEMO865": {name: "Wig Out!", quantity: 1},
  "DEMO1100": {name: "Wig Out!", quantity: 1},
  "DEMO1211": {name: "Wing It", quantity: 1},
  "DEMO868": {name: "Wits & Wagers", quantity: 1},
  "DEMO869": {name: "Wits & Wagers Family", quantity: 1},
  "DEMO1628": {name: "Wizards Wanted", quantity: 1},
  "DEMO3000": {name: "Wobble King", quantity: 1},
  "DEMO3011": {name: "Women in Science 500p", quantity: 1},
  "DEMO552": {name: "Wonders of Science", quantity: 1},
  "DEMO1549": {name: "Word a Round", quantity: 1},
  "DEMO872": {name: "Word on the Street", quantity: 1},
  "DEMO1171": {name: "Word on the street junior", quantity: 1},
  "DEMO3118": {name: "Word on the Street Junior", quantity: 1},
  "DEMO1054": {name: "Word Slam", quantity: 1},
  "DEMO3103": {name: "Wordamelon", quantity: 1},
  "DEMO875": {name: "World Map Henricus Hondus 1000p", quantity: 1},
  "DEMO877": {name: "Yahtzee", quantity: 1},
  "DEMO3102": {name: "Yikers!", quantity: 1},
  "DEMO3231": {name: "Yikers!", quantity: 1},
  "DEMO1670": {name: "Zangle", quantity: 1},
  "DEMO1712": {name: "Zangle", quantity: 1},
  "DEMO1219": {name: "Zero Down", quantity: 1},
  "DEMO880": {name: "Zeus On The Loose", quantity: 1},
  "DEMO881": {name: "Zeus On The Loose", quantity: 1},
  "DEMO882": {name: "Zeus On The Loose", quantity: 1},
  "DEMO1277": {name: "Zeus On The Loose", quantity: 1},
  "DEMO883": {name: "Zimbbos", quantity: 1},
  "DEMO1287": {name: "Zingo", quantity: 1},
  "DEMO3175": {name: "Zingo", quantity: 1},
  "DEMO933": {name: "Zingo 1-2-3", quantity: 1},
  "DEMO888": {name: "Zingo Sight Words", quantity: 1},
  "DEMO890": {name: "Zingo Word Builder", quantity: 1},
  "DEMO887": {name: "Zingo! 1-2-3", quantity: 1},
  "DEMO889": {name: "Zingo! Time-Telling", quantity: 1},
  "DEMO891": {name: "Zingo! Word Builder", quantity: 1},
  "DEMO894": {name: "Zombie Dice", quantity: 1},
  "DEMO3137": {name: "Zombie Kidz", quantity: 1}
};
